    - name: Add apt-key, mongo repo and update
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "D68FA50FEA312927"
      tags: install  
    - name: Repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
      tags: install  
    - name: Update     
      apt:
        update_cache: yes
      tags: install  
    - name: Install mongo
      apt:
        name: mongodb-org
        state: present
      tags: install   
    - name: Mongo service
      systemd: 
        name: mongod
        state: started
        enabled: yes
      tags: install 