---
- name: MongoDB
  hosts: all
  become: true
  vars: 
    key_id: D68FA50FEA312927
  tasks:
    - name: Add apt-key, mongo repo and update
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ key_id }}"
    - name: Repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: Update     
      apt:
        update_cache: yes
    - name: Install mongo
      apt:
        name: mongodb-org
        state: present 
    - name: Mongo service
      systemd: 
        name: mongod
        state: started
        enabled: yes
