---
plugin: gcp_compute
projects:
  - infra-253411
service_account_file: ~/.ssh/infra.json
auth_kind: serviceaccount
hostnames:
  - name
groups:
  app: "'-app' in name"
  db: "'-db' in name"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  internal_ip: networkInterfaces[0].networkIP
